import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Anime Blog",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className="bg-[linear-gradient(rgb(0_0_0/0.5),rgb(0_0_0/0.5)),url(https://picgo-elaina.oss-cn-chengdu.aliyuncs.com/typora/202509101118191.jpg)]
        bg-no-repeat
        bg-cover
        bg-center
        bg-fixed
        "
        >
        {children}
      </body>
    </html>
  );
}
